### ISSUE TITLE
label question

### ISSUE THREAD

**Issue by liuderwhat** [DavidNepozitek/Style2Vec#1]
I cannot find "train_no_dup_out.json". Can you provide this file? or tell me where it is.
I replace "train_no_dup_out.json" with "train_no_dup.json". I get a error message 'Items' in txt file.
It is in style2vec1.py line 152.

**Comment by DavidNepozitek** [comment]
Hi,
firstly I should mention that this repository was intented to serve rather as an inspiration than anything else. So I can't guarantee that everything is going to run smoothly. 

In this particular case, I prefiltered the original dataset so it contains only wearable products. Unfortunately, the prefiltering code is not included in this repo. I've attached the files you need

[processed_labels.zip](https://github.com/DavidNepozitek/Style2Vec/files/4239052/processed_labels.zip)
