### ISSUE TITLE
Pretrained model?

### ISSUE THREAD

**Issue by jxtps** [DavidNepozitek/Style2Vec#2]
Nice work on Style2Vec - the results look great! 

Any chance you'd be willing to publish a pretrained model? 

Looked like you had made space for it in the project layout, but there's only a .gitkeep file in there?

Thanks!

**Comment by DavidNepozitek** [comment]
Hi,
yes, I still should have the pre-trained model somewhere. I can share it if I find a convenient way. 
However, it can take a week or two until I get to this.

**Comment by jxtps** [comment]
I've seen other projects put the model files into a release, like this: https://github.com/qubvel/efficientnet/releases/tag/v0.0.1 without including them in the repository itself. 

I'm not sure exactly how that works as I haven't done a release on github. Maybe you can add arbitrary files to it somehow?

**Comment by jxtps** [comment]
Were you able find the pre-trained model? Would be really great to get access to it. Thanks! 

https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository shows how to add arbitrary files to a release: in the release workflow you can just drag & drop them onto the "binaries box". Looks pretty convenient ;)

**Comment by jxtps** [comment]
Also [from the docs](https://docs.github.com/en/github/administering-a-repository/about-releases): "Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage." so should fit without issues?

**Comment by DavidNepozitek** [comment]
Hey,
I'm sorry for my late response, I'm finishing my bachelor thesis so I don't have much time.

I've found the pretrained model and released it here: https://github.com/DavidNepozitek/Style2Vec/releases/tag/v0.1
I hope you manage to make it work because there were some issues with saving the model in the version of TensorFlow I used at that time.

**Comment by jxtps** [comment]
Excellent, will give it a spin this week, thank you for posting it!
