### ISSUE TITLE
Error when running style2vec.py

### ISSUE THREAD

**Issue by ALI7861111** [DavidNepozitek/Style2Vec#4]
when i run style2vec.py
when the fitting process starts it exists with an error:
When i check error in the txt file the error is . There is no label folder in data directory.
[Errno 2] No such file or directory: '../data/label/train_no_dup_out.json'

**Comment by DavidNepozitek** [comment]
Hi,
firstly I should mention that this repository was intended to serve rather as an inspiration than anything else. So I can't guarantee that everything is going to run smoothly. Also, the codebase is quite old.

Nevertheless, I've already answered your question in #1
